// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ZoneInterviewTask_PeterOlofinmoyin.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class NavigateToBBCEastEndersNextEpisodePageFeature : Xunit.IClassFixture<NavigateToBBCEastEndersNextEpisodePageFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "NavigateToBBCEastEndersNextEpisodePage.feature"
#line hidden
        
        public NavigateToBBCEastEndersNextEpisodePageFeature(NavigateToBBCEastEndersNextEpisodePageFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Navigate To BBC EastEnders Next Episode Page", "\tIn order to avoid missing EastEnders\r\n\tAs a user on the BBC websites\r\n\tI want to" +
                    " find out when the next episode occurs", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
 #line 7
 testRunner.Given("I\'m on the \"https://www.bbc.co.uk\" homepage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Search for EastEnders next episode")]
        [Xunit.TraitAttribute("FeatureTitle", "Navigate To BBC EastEnders Next Episode Page")]
        [Xunit.TraitAttribute("Description", "Search for EastEnders next episode")]
        [Xunit.TraitAttribute("Category", "InputfieldTesting")]
        [Xunit.TraitAttribute("Category", "StateTransitioningTesting")]
        public virtual void SearchForEastEndersNextEpisode()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search for EastEnders next episode", null, new string[] {
                        "InputfieldTesting",
                        "StateTransitioningTesting"});
#line 11
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
 this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "criteria"});
            table1.AddRow(new string[] {
                        "EastEnders"});
#line 12
 testRunner.When("I search for EastEnders Episode Next on schedule:", ((string)(null)), table1, "When ");
#line 15
 testRunner.Then("I am redirected to the Next Episodes screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.TheoryAttribute(DisplayName="Navigate to EastEnders schedule page on BBC website by entering url manually.")]
        [Xunit.TraitAttribute("FeatureTitle", "Navigate To BBC EastEnders Next Episode Page")]
        [Xunit.TraitAttribute("Description", "Navigate to EastEnders schedule page on BBC website by entering url manually.")]
        [Xunit.TraitAttribute("Category", "EquivalencePartitionTesting")]
        [Xunit.InlineDataAttribute("https://www.bbc.co.uk/programmes/b006m86d/broadcasts/upcoming", new string[0])]
        public virtual void NavigateToEastEndersSchedulePageOnBBCWebsiteByEnteringUrlManually_(string episodesPage, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "EquivalencePartitionTesting"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Navigate to EastEnders schedule page on BBC website by entering url manually.", null, @__tags);
#line 20
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
 this.FeatureBackground();
#line 21
 testRunner.When(string.Format("I request to navigate to \"{0}\"", episodesPage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 22
 testRunner.Then("I am redirected to the Next Episodes screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                NavigateToBBCEastEndersNextEpisodePageFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                NavigateToBBCEastEndersNextEpisodePageFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
